name: Deploy to GitHub Pages
description: Deploy the project to GitHub Pages
runs:
  using: "composite"
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  steps:
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: "./build"
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
