name: Deploy to GitHub Pages
on: [push]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: "./.github/actions/build"
      - name: Deploy
        uses: "./.github/actions/deploy"
