name: Deploy to GitHub Pages
on: [push]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "./.github/actions/deploy-to-github-pages"
