name: Deploy to GitHub Pages
on: [push]
defaults:
  run:
    working-directory: frontend
jobs:
  deploy-to-digitalocean:
    runs-on: ubuntu-latest
    environment: digitalocean
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: "./.github/actions/build"
        with:
          working-directory: frontend
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: lukarusadze/actionator:latest
      - name: Deploy to DigitalOcean App Platform
        uses: digitalocean/app_action@v1.1.5
        with:
          app_name: lukarusadze-actionator
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
