name: Deploy to GitHub Pages
on: [push]
defaults:
  run:
    working-directory: frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: "./.github/actions/build"
        with:
          working-directory: frontend
